StylesPath = docs/styles
MinAlertLevel = warning

Vocab = JuMP

[*.md]
BasedOnStyles = Vale, Google
TokenIgnores =          \
    \$.+?\$,            \
    \]\(@(ref|id).+?\), \
    AMPL: A Modeling Language for Mathematical Programming

[*.jl]
BasedOnStyles = Vale, Google

# TODO(odow): fix all of these
Google.Ellipses = OFF
Google.EmDash = OFF
Google.Exclamation = OFF
Google.FirstPerson = OFF
Google.OptionalPlurals = OFF
Google.Quotes = OFF
Google.Units = OFF
Vale.Spelling = OFF
Vale.Terms = OFF

[LICENSE.md]
Google.Colons = NO

[docs/src/moi/*]
Google.FirstPerson = NO
Vale.Spelling = OFF

; TODO(odow): remove at some point
[docs/src/packages/*]
Google.Colons = NO
Google.Ellipses = NO
Google.EmDash = NO
Google.Exclamation = NO
Google.FirstPerson = NO
Google.Latin = NO
Google.OptionalPlurals = NO
Google.Periods = NO
Google.Quotes = NO
Vale.Spelling = NO
