# ============================= jump-dev packages ============================ #

[AmplNLWriter]
    rev = "od/readme"
[BARON]
    rev = "od/readme"
[Cbc]
    rev = "od/readme"
[Clp]
    rev = "od/readme"
[CPLEX]
    rev = "od/readme"
[CSDP]
    rev = "od/readme"
# [DiffOpt]
# [Dualization]
[ECOS]
    rev = "od/readme"
[GLPK]
    rev = "od/readme"
[Gurobi]
    rev = "od/readme"
[HiGHS]
    rev = "od/readme"
[Ipopt]
    rev = "od/readme"
[KNITRO]
    rev = "od/readme"
[MiniZinc]
    rev = "od/readme"
[MosekTools]
    rev = "od/readme"
[MultiObjectiveAlgorithms]
    rev = "od/readme"
[Pajarito]
    rev = "od/readme"
[Pavito]
    rev = "od/readme"
[Penopt]
    rev = "od/readme"
[SCS]
    rev = "od/readme"
[SDPA]
    rev = "od/readme"
[SDPNAL]
    rev = "od/readme"
[SDPT3]
    rev = "od/readme"
[SeDuMi]
    rev = "od/readme"
[Xpress]
    rev = "od/readme"

# ======================= Updated non-jump-dev packages ====================== #

[NEOSServer]
  user = "odow"
  rev = "od/readme"
[PATHSolver]
  user = "chkwon"
  rev = "od/readme"
  
# =========================== Non-jump-dev packages ========================== #

[Alpine]
  user = "lanl-ansi"
[CDCS]
  user = "oxfordcontrol"
[CDDLib]
  user = "JuliaPolyhedra"
[Clarabel]
  user = "oxfordcontrol"
[COPT]
  user = "COPT-Public"
[COSMO]
  user = "oxfordcontrol"
[DAQP]
  user = "darnstrom"
  rev = "main"
[EAGO]
  user = "PSORLab"
[GAMS]
  user = "GAMS-dev"
[Hypatia]
  user = "chriscoey"
[Juniper]
  user = "lanl-ansi"
[MadNLP]
  user = "MadNLP"
[NLopt]
  user = "JuliaOpt"
[OSQP]
  user = "osqp"
[ProxSDP]
  user = "mariohsouto"
[SCIP]
  user = "scipopt"
[Tulip]
  user = "ds4dm"
