# ============================= jump-dev packages ============================ #

[AmplNLWriter]
    rev = "od/readme"
[BARON]
    rev = "od/readme"
[Cbc]
    rev = "a78e129"
[Clp]
    rev = "3358ee6"
[CPLEX]
    rev = "8e6f211"
[CSDP]
    rev = "3a2e4c7"
[DiffOpt]
    rev = "od/readme"
[Dualization]
    rev = "od/readme"
[ECOS]
    rev = "80d1a927b05b04360b7a8e6800f5ae13bc6a1494"
[GLPK]
    rev = "dd835dc425fe8995d965da8a57b4a3a1764cf8da"
[Gurobi]
    rev = "od/readme"
[HiGHS]
    rev = "b0ab8361558fc63873a5cf380d335409f02d8863"
[Ipopt]
    rev = "od/readme"
[KNITRO]
    rev = "3fb7c61e886b1b06d9f5cd646e194da638c93355"
[MiniZinc]
    rev = "od/readme"
[MosekTools]
    rev = "od/readme"
[MultiObjectiveAlgorithms]
    rev = "b4413a1ef3b7d28045cedba4e68e5e4959c8bb12"
    has_html = true
[Pajarito]
    rev = "od/readme"
[Pavito]
    rev = "od/readme"
[Penopt]
    rev = "od/readme"
[SCS]
    rev = "od/readme"
[SDPA]
    rev = "5d15d3c292cd25b461f524aaaf8eb5ecb8e08b0d"
[SDPNAL]
    rev = "87b516fd3db316de8aa12681295138df335feed4"
[SDPT3]
    rev = "od/readme"
[SeDuMi]
    rev = "od/readme"
[Xpress]
    rev = "od/readme"

# ======================= Updated non-jump-dev packages ====================== #

# [Alpine]
#   user = "lanl-ansi"
# [CDCS]
#   user = "oxfordcontrol"
# [CDDLib]
#   user = "JuliaPolyhedra"
# [Clarabel]
#   user = "oxfordcontrol"
#   has_html = true
# [COPT]
#   user = "COPT-Public"
# [COSMO]
#   user = "oxfordcontrol"
#   has_html = true
# [DAQP]
#   user = "darnstrom"
#   rev = "main"
# [EAGO]
#   user = "PSORLab"
# [GAMS]
#   user = "GAMS-dev"
# [Hypatia]
#   user = "chriscoey"
# [Juniper]
#   user = "lanl-ansi"
# [MadNLP]
#   user = "MadNLP"
[NEOSServer]
  user = "odow"
  rev = "v1.0.2"
  filename = "README.md"
# [NLopt]
#   user = "JuliaOpt"
# [OSQP]
#   user = "osqp"
[PATHSolver]
  user = "chkwon"
  rev = "od/readme"
  filename = "README.md"
# [ProxSDP]
#   user = "mariohsouto"
# [SCIP]
#   user = "scipopt"
# [Tulip]
#   user = "ds4dm"
