# ============================= jump-dev packages ============================ #

[AmplNLWriter]
    rev = "v1.1.0"
[BARON]
    rev = "f5f4c9c8f27e0ef8644d65fb956f3bca5305b45e"
[Cbc]
    rev = "a78e129"
[Clp]
    rev = "3358ee6"
[CPLEX]
    rev = "8e6f211"
[CSDP]
    rev = "3a2e4c7"
[DiffOpt]
    rev = "od/readme"
[Dualization]
    rev = "13974285d5ed6f678e4b96aafb764dad5238aac0"
[ECOS]
    rev = "80d1a927b05b04360b7a8e6800f5ae13bc6a1494"
[GLPK]
    rev = "dd835dc425fe8995d965da8a57b4a3a1764cf8da"
[Gurobi]
    rev = "72ee279373d7559e32050c35735d3fc803a7bb12"
[HiGHS]
    rev = "b0ab8361558fc63873a5cf380d335409f02d8863"
[Ipopt]
    rev = "v1.2.1"
[KNITRO]
    rev = "3fb7c61e886b1b06d9f5cd646e194da638c93355"
[MiniZinc]
    rev = "21d5829c2838959e2ec2d2952495c83f43b271b7"
[MosekTools]
    rev = "e2ed9bc174c6aaa68e457077529d49be52ecbc37"
[MultiObjectiveAlgorithms]
    rev = "b4413a1ef3b7d28045cedba4e68e5e4959c8bb12"
    has_html = true
[Pajarito]
    rev = "2c008ee52bff34c41ebd394e2daae9eb32387e4b"
[Pavito]
    rev = "c0f3d81d9e9fff2963b872cf84fea35bfcf8b1d1"
[Penopt]
    rev = "486f07d3f3a11f12012ea3ada702a3ee55c8fdc5"
[SCS]
    rev = "ef7cb4e38e987fcbbdeebd50bd4c211633328150"
[SDPA]
    rev = "5d15d3c292cd25b461f524aaaf8eb5ecb8e08b0d"
[SDPNAL]
    rev = "87b516fd3db316de8aa12681295138df335feed4"
[SDPT3]
    rev = "02f69fb87941691722176f77a48933ff7f7a78b4"
[SeDuMi]
    rev = "47b4497cab3ce59ec7f65cff455bb2014981d4b4"
[Xpress]
    rev = "od/readme"

# ======================= Updated non-jump-dev packages ====================== #

# [Alpine]
#   user = "lanl-ansi"
# [CDCS]
#   user = "oxfordcontrol"
# [CDDLib]
#   user = "JuliaPolyhedra"
# [Clarabel]
#   user = "oxfordcontrol"
#   has_html = true
# [COPT]
#   user = "COPT-Public"
# [COSMO]
#   user = "oxfordcontrol"
#   has_html = true
# [DAQP]
#   user = "darnstrom"
#   rev = "main"
# [EAGO]
#   user = "PSORLab"
# [GAMS]
#   user = "GAMS-dev"
# [Hypatia]
#   user = "chriscoey"
# [Juniper]
#   user = "lanl-ansi"
# [MadNLP]
#   user = "MadNLP"
[NEOSServer]
  user = "odow"
  rev = "v1.0.2"
  filename = "README.md"
# [NLopt]
#   user = "JuliaOpt"
# [OSQP]
#   user = "osqp"
[PATHSolver]
  user = "chkwon"
  rev = "08848c165747695e7a4dcbb86a657e2347ca7149"
  filename = "README.md"
# [ProxSDP]
#   user = "mariohsouto"
# [SCIP]
#   user = "scipopt"
# [Tulip]
#   user = "ds4dm"
