# ============================= jump-dev packages ============================ #

[AmplNLWriter]
    rev = "od/readme"
[BARON]
    rev = "od/readme"
[Cbc]
    rev = "od/readme"
[Clp]
    rev = "od/readme"
[CPLEX]
    rev = "od/readme"
[CSDP]
    rev = "od/readme"
[DiffOpt]
[Dualization]
[ECOS]
    rev = "od/readme"
[GLPK]
    rev = "od/readme"
[Gurobi]
    rev = "od/readme"
[HiGHS]
    rev = "od/readme"
[Ipopt]
    rev = "od/readme"
[KNITRO]
[MiniZinc]
    rev = "od/readme"
[MosekTools]
[MultiObjectiveAlgorithms]
[Pajarito]
    rev = "main"
[Pavito]
[Penopt]
[SCS]
    rev = "od/readme"
[SDPA]
[SDPNAL]
[SDPT3]
[SeDuMi]
[Xpress]

# =========================== Non-jump-dev packages ========================== #

# [Alpine]
#   user = "lanl-ansi"
# [CDCS]
#   user = "oxfordcontrol"
# [CDDLib]
#   user = "JuliaPolyhedra"
# [Clarabel]
#   user = "oxfordcontrol"
# [COPT]
#   user = "COPT-Public"
# [COSMO]
#   user = "oxfordcontrol"
# [DAQP]
#   user = "darnstrom"
#   rev = "main"
# [EAGO]
#   user = "PSORLab"
# [GAMS]
#   user = "GAMS-dev"
# [Hypatia]
#   user = "chriscoey"
# [Juniper]
#   user = "lanl-ansi"
# [MadNLP]
#   user = "MadNLP"
# [NLopt]
#   user = "JuliaOpt"
# [OSQP]
#   user = "osqp"
# [PATHSolver]
#   user = "chkwon"
# [ProxSDP]
#   user = "mariohsouto"
# [SCIP]
#   user = "scipopt"
# [Tulip]
#   user = "ds4dm"
